### ISSUE TITLE
Include metadata schema website on DCP status page https://humancellatlas.github.io/

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/humancellatlas.github.io#1]

**Comment by mweiden** [comment]
I've put an entry into the website for this though its interpretation is a little ambiguous for a couple reasons
* A single deployment covers all environments: `{dev, integration, staging, prod}` - I've chosen to label this `prod`, but this is a little misleading as its functionality bleeds into other deployment environments
* The site is served directly from cloudfront and s3, so there's not really much additional system health to check other than cloudfront and s3 themselves
* As far as I can tell, https://schema.humancellatlas.org/health is automatically returned by cloudfront and doesn't reflect anything meaningful about the health of the system

**Comment by sampierson** [comment]
_As far as I can tell, https://schema.humancellatlas.org/health is automatically returned by cloudfront and doesn't reflect anything meaningful about the health of the system_

It is however telling you that DNS, CloudFront and other things are correctly configured.  That's all we need.
